name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Build and push the API image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: user/app:latest
      -
        name: Build and push the Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front-end-nextjs
          push: true
          tags: user/app:latest
